### PR TITLE
scoped-properties -> settings

### PR DESCRIPTION
**Pull request by ollpu**
Hey! I've noticed this plugin had one deprecation, so I decided to implement the easy fix. Let's hope we can get this merged before Atom 1.0 :smile:!

(Related issues, all duplicates of each other: #5 #6 #7 #8)

### CODE REVIEW

**Comment by bnferguson** [comment]
I was coming here to do this! :+1:

**Comment by ollpu** [comment]
There seems to be no activity on this repository by @bleikamp. I've sent him an email as well, no response. Should someone take this plugin over?

**Comment by bnferguson** [comment]
@ollpu - Things are pretty busy at work right now so he may be a little slow to respond. I may be seeing him in person next week, I'll see if I can get added as a collaborator to help get some of these through during crazier times.

**Comment by ollpu** [comment]
Okay... we'll see.

**Pull request merged**
